<a href="https://colab.research.google.com/github/vikrampal12345/Machine_learning/blob/main/6_Feature_Encoding_categorical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# ordinal data - ordinal encoding - input data
# nominal data - one hot encoding
# output data - label encoding

import pandas as pd
import numpy as np

df = pd.read_csv("/content/customer.csv")
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [ ]:
df = df.iloc[:,2:]
df

In [20]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop('purchased', axis=1), df['purchased'], test_size=0.2 )

X_train

     review education
15     Poor        UG
45     Poor        PG
34  Average    School
37  Average        PG
47     Good        PG
3      Good        PG
10     Good        UG
30  Average        UG
33     Good        PG
27     Poor        PG
42     Good        PG
31     Poor    School
49     Good        UG
20  Average    School
25     Good    School
32  Average        UG
6      Good    School
8   Average        UG
13  Average    School
46     Poor        PG
12     Poor    School
28     Poor    School
44  Average        UG
43     Poor        PG
41     Good        PG
35     Poor    School
39     Poor        PG
36     Good        UG
40     Good    School
1      Poor        UG
5   Average    School
24  Average        PG
38     Good    School
18     Good    School
21  Average        PG
19     Poor        PG
23     Good    School
4   Average        UG
9      Good        UG
26     Poor        PG

In [27]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

oe.fit(X_train)
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [ ]:
X_train

In [29]:
oe.categories_        # check categories and their datatype

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Encoder is used only for the output data (y)

In [ ]:
# labelEncoder..

In [30]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(y_train)

LabelEncoder()

In [31]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [32]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

y_train

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0])