<a href="https://colab.research.google.com/github/vikrampal12345/Machine_learning/blob/main/9_train_Pipelines_A_Z_Scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pipelines chains together multiple steps so that the output of each step is used as input to the next step.

Pipelines make it easy to apply the same preprocessing to train and test!

In [144]:
# pipeline
# missing values -> encoding -> scaling -> feature selection -> train the model

In [145]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer

In [146]:
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [148]:
df.drop(columns = ['class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone'], inplace=True)

In [149]:
df

     survived  pclass     sex   age  sibsp  parch     fare embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [150]:
# step 1 -> train/test/split

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['survived']),
                                                    df['survived'], test_size = 0.2, random_state=42)

In [151]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: survived, Length: 712, dtype: int64

In [152]:
X_train.head()

     pclass     sex   age  sibsp  parch     fare embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [153]:
X_test.head()

     pclass     sex   age  sibsp  parch     fare embarked
709       3    male   NaN      1      1  15.2458        C
439       2    male  31.0      0      0  10.5000        S
840       3    male  20.0      0      0   7.9250        S
720       2  female   6.0      0      1  33.0000        S
39        3  female  14.0      1      0  11.2417        C

In [154]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

In [155]:
# apply simpleImputer for the missing data

# si_age = SimpleImputer()
# si_embarked = SimpleImputer(strategy='most_frequent')

# column_transformer =

# this is not proper way to write the code the region is last in the page

In [156]:
# this is not proper way to write the code the region is last in the page

# from sklearn.compose import ColumnTransformer

# transformer  = ColumnTransformer(transformers=[
#     ('tnf1', SimpleImputer(), ['age']),
#     ('tnf2', SimpleImputer(strategy = 'most_frequent'), ['embarked']),
#     ('tnf3', OneHotEncoder(sparse_output=False,drop='first'), ['sex']),
#     ('tnf4', OneHotEncoder(sparse_output=False,drop='first'), ['embarked']),
# ], remainder = 'passthrough')

In [157]:
# from sklearn.pipeline import Pipeline, make_pipeline
# from sklearn.compose import ColumnTransformer

# embarked_pipe = Pipeline([
#     ('imputer', SimpleImputer(strategy = 'most_frequent')),
#     ('encoder', OneHotEncoder(sparse_output=False, drop='first'))
# ])

# transformer  = ColumnTransformer(transformers=[
#     ('tnf1', SimpleImputer(), ['age']),
#     ('tnf2', OneHotEncoder(sparse_output=False,drop='first'), ['sex']),
#     ('embarked_pipeline', embarked_pipe, ['embarked']),
# ], remainder = 'passthrough')

# X_train = transformer.fit_transform(X_train)
# X_test = transformer.transform(X_test)

# clf = DecisionTreeClassifier()
# clf.fit(X_train,y_train)

In [158]:
# y_pred = clf.predict(X_test)
# y_pred

In [159]:
# from sklearn.metrics import accuracy_score

# accuracy_score(y_test, y_pred)

# creating pipeline

In [160]:
# imputation transformer (Nan replace by the value)

trf1 = ColumnTransformer([
    ('impute_age', SimpleImputer(),[2]),
     ('impute_embarked', SimpleImputer(strategy='most_frequent'),[6])# use index in the pipeline,
], remainder='passthrough')             # because it return the numpy array and the no dataframe. no dataframe means no column

In [161]:
# one hot encoding
trf2 = ColumnTransformer([
    ('ohe_sex_embarked', OneHotEncoder(sparse_output=False, handle_unknown='ignore'),[1,6])
], remainder='passthrough')

In [162]:
# scaling
trf3 = ColumnTransformer(transformers=[
    ('scale', MinMaxScaler(), slice(0, 10))
    ])

In [163]:
# Feature selection
from sklearn.feature_selection import SelectKBest, chi2
trf4 = SelectKBest(score_func=chi2, k=8)

In [164]:
# train the model
trf5 = DecisionTreeClassifier()

# creating pipeline here

In [170]:
pipe = Pipeline([
    ('trf1', trf1),
    ('trf2', trf2),
    ('trf3', trf3),
    ('trf4', trf4),
    ('trf5', trf5)
    ])

# Pipeline Vs make_pipeline

Pipeline requires naming of steps, make_pipeline does not.

(Same applies to ColumnTransformer vs make_column_transformer)

In [166]:
# alternate syntax

# pipe = make_pipeline(trf1, trf2, trf3, trf4, trf5)

In [171]:
#
pipe.fit(X_train, y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('trf3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('trf4',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x7a8f6dc5e200>)),
                ('trf5', DecisionTreeClassifier())])

# Explore the Pipeline

In [172]:
# code here
pipe.named_steps

{'trf1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'trf2': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 6])]),
 'trf3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'trf4': SelectKBest(k=8, score_func=<function chi2 at 0x7a8f6dc5e200>),
 'trf5': DecisionTreeClassifier()}

In [174]:
pipe.named_steps['trf1']  # target - check the mean

ColumnTransformer(remainder='passthrough',
                  transformers=[('impute_age', SimpleImputer(), [2]),
                                ('impute_embarked',
                                 SimpleImputer(strategy='most_frequent'),
                                 [6])])

In [176]:
pipe.named_steps['trf1'].transformers_  # which transformer connected then show

[('impute_age', SimpleImputer(), [2]),
 ('impute_embarked', SimpleImputer(strategy='most_frequent'), [6]),
 ('remainder',
  FunctionTransformer(accept_sparse=True, check_inverse=False,
                      feature_names_out='one-to-one'),
  [0, 1, 3, 4, 5])]

In [177]:
pipe.named_steps['trf1'].transformers_[0]

('impute_age', SimpleImputer(), [2])

In [178]:
pipe.named_steps['trf1'].transformers_[0][1] # simpleImputer

SimpleImputer()

In [179]:
pipe.named_steps['trf1'].transformers_[0][1].statistics_

array([29.49884615])

In [180]:
pipe.named_steps['trf1'].transformers_[1][1].statistics_  # Embarked

array(['S'], dtype=object)

In [181]:
# Display pipeline

from sklearn import set_config
set_config(display='diagram')

In [182]:
# predict
y_pred = pipe.predict(X_test)

In [183]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6256983240223464

# Cross Validation using Pipeline

In [184]:
# cross validation using cross_val_score

from sklearn.model_selection import cross_val_score

cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy',).mean()

np.float64(0.6391214419383433)

# GridSearch using Pipeline

In [185]:
# gridsearchcv
params = {
    'trf5__max_depth': [1,2,3,4,5,None]
}

In [186]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trf1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('trf2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe_sex_embarked',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         [1,
                                                                          6])])),
                                       ('trf3',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('trf4',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x7a8f6dc5e200>)),
                                       ('trf5', DecisionTreeClassifier())]),
             param_grid={'trf5__max_depth': [1, 2, 3, 4, 5, None]},
             scoring='accuracy')

In [187]:
grid.best_score_

np.float64(0.6391214419383433)

In [188]:
grid.best_params_

{'trf5__max_depth': 2}

In [194]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [195]:
import shutil

shutil.copy(
    '/content/pipe.pkl',
    '/content/drive/MyDrive/pipe.pkl'
)

'/content/drive/MyDrive/pipe.pkl'

# Exporting the Pipeline

In [193]:
# export
import pickle
pickle.dump(pipe, open('pipe.pkl', 'wb'))

## OneHotEncoder Parameters – Short Notes

### `sparse_output=False`

* Converts the encoded output into a **NumPy array**.
* Default output is a **sparse matrix** to save memory.
* Useful for **small datasets** and easier visualization.

```python
OneHotEncoder(sparse_output=False)
```

**Output Type:**

* `False` → NumPy array (`ndarray`)
* `True` (default) → Sparse matrix (`csr_matrix`)

---

### `drop='first'`

* Removes the first category after one-hot encoding.
* Prevents the **dummy variable trap** (multicollinearity).
* Reduces redundant columns.

```python
OneHotEncoder(drop='first')
```

**Example:**

Categories: `['Red', 'Blue', 'Green']`

Without `drop='first'`:

| Blue | Green | Red |
| ---- | ----- | --- |
| 1    | 0     | 0   |
| 0    | 1     | 0   |
| 0    | 0     | 1   |

With `drop='first'`:

| Green | Red |         |
| ----- | --- | ------- |
| 0     | 0   | ← Blue  |
| 1     | 0   | ← Green |
| 0     | 1   | ← Red   |

---

### Important Note

* These parameters are used during **encoding**, not **scaling**.
* Scaling is performed using tools like:

  * `StandardScaler`
  * `MinMaxScaler`
  * `RobustScaler`

## Pipeline + ColumnTransformer – Notes

### Why Use a Pipeline?

A `Pipeline` applies multiple preprocessing steps **sequentially** to the same column.

Example:

```text id="j3c1y4"
embarked
   ↓
SimpleImputer
   ↓
OneHotEncoder
```

Without a `Pipeline`, `ColumnTransformer` applies transformations independently.

---

### Required Imports

```python id="krm9q7"
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
```

---

### Create a Pipeline for `embarked`

```python id="n6f8w2"
embarked_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(drop='first', sparse_output=False))
])
```

#### Why these steps?

* `SimpleImputer(strategy='most_frequent')`

  * Fills missing values with the most common category.
  * Example: `S, C, NaN, S → S, C, S, S`

* `OneHotEncoder(drop='first', sparse_output=False)`

  * Converts categories into numerical columns.
  * `drop='first'` avoids the dummy variable trap.
  * `sparse_output=False` returns a NumPy array instead of a sparse matrix.

---

### Create the ColumnTransformer

```python id="z5d1a8"
transformer = ColumnTransformer([
    ('age_imputer', SimpleImputer(), ['age']),

    ('sex_encoder',
     OneHotEncoder(drop='first', sparse_output=False),
     ['sex']),

    ('embarked_pipeline',
     embarked_pipe,
     ['embarked'])
], remainder='passthrough')
```

---

### Fit and Transform

```python id="m7r4x9"
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)
```

---

## Why Use These Important Steps?

| Step                  | Purpose                                              |
| --------------------- | ---------------------------------------------------- |
| `SimpleImputer()`     | Fills missing values                                 |
| `OneHotEncoder()`     | Converts categorical data to numbers                 |
| `drop='first'`        | Prevents multicollinearity                           |
| `sparse_output=False` | Returns a normal NumPy array                         |
| `Pipeline()`          | Applies multiple steps to the same column            |
| `ColumnTransformer()` | Applies different preprocessing to different columns |
| `fit_transform()`     | Learns parameters and transforms training data       |
| `transform()`         | Applies learned parameters to test data              |

---

## Remember

```text id="b9k2u6"
Pipeline → Same column, multiple steps

ColumnTransformer → Different columns, different transformations
```