<a href="https://colab.research.google.com/github/vikrampal12345/Machine_learning/blob/main/12_Missing_Everytype_DataHandling/4_KNN_Imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#

# KNN Imputer

it is under multivariate imputation

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [5]:
df1 = sns.load_dataset('titanic')
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
df = df1.iloc[:,[0,1,3,6]]
df.head()

   survived  pclass   age     fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [7]:
df.isnull().mean() * 100

survived     0.00000
pclass       0.00000
age         19.86532
fare         0.00000
dtype: float64

In [10]:
x = df.drop('survived', axis=1)
y = df.iloc[:,0]

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=2)

X_train.shape, X_test.shape

((712, 3), (179, 3))

In [42]:
knn = KNNImputer(n_neighbors=1, weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [18]:
(pd.DataFrame(X_train_trf, columns=X_train.columns)).isnull().mean() * 100

pclass    0.0
age       0.0
fare      0.0
dtype: float64

In [43]:
lr = LogisticRegression()

lr.fit(X_train_trf, y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test, y_pred)

0.7206703910614525

In [20]:
# Comparision with Simple Imputer --> mean

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [21]:
lr = LogisticRegression()

lr.fit(X_train_trf2, y_train)

y_pred = lr.predict(X_test_trf2)

accuracy_score(y_test, y_pred)

0.6927374301675978