<a href="https://colab.research.google.com/github/vikrampal12345/Machine_learning/blob/main/12_Missing_Everytype_DataHandling/MICE_algorithm_multivariate_chained_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mulitivariate Imputation by Chained Equations for Missing Value

# MICE Algorithm/iterative imputer

In [ ]:
# Assumptions
# 1. MCAR (Missing completely at random)
# 2. MAR (Missing at random)  - MICE Algorithm apply
# 3. MNAR (Missing not at random)

In [ ]:
# Advantages & Disadvantage
# 1. accurates
# 2. slow
# 3. memory problem (occupy space)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv("/content/50_Startups.csv")
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
df.isnull().mean() * 100

R&D Spend          0.0
Administration     0.0
Marketing Spend    0.0
State              0.0
Profit             0.0
dtype: float64